version: '3.8'

services:
  backend_node_ext:
    image: nitinsaa1999/testproject-backend_node_ext
    container_name: nitin_backend_ext
    working_dir: /app
    build:
      context: ./
      dockerfile: DockerfileExt
    # volumes:
    #   - "D:/Test Project/Backend:/app:rw"
    env_file: ./.env.prod
    environment:
      NODE_ENV: production
    ports:
      - 8005:8000
    restart: unless-stopped
    # command: sleep infinity
    networks:
      - my-ext-network

networks:
  my-ext-network:
    driver: bridge
    external: true