version: '3.8'

services:
  backend_node:
    image: nitinsaa1999/testproject-backend_node
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - D:\Test Project\Backend\Test-Backend:/app
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000