version: '3.8'

services:
  backend_node_prod:
    image: nitinsaa1999/testproject-backend_node_prod
    container_name: nitin_backend_prod
    working_dir: /app
    build:
      context: ./
      dockerfile: DockerfileProd
    # volumes:
    #   - "D:/Test Project/Backend:/app:rw"
    env_file: ./.env.prod
    environment:
      NODE_ENV: production
    ports:
      - 8002:8000
    restart: unless-stopped
    command: sleep infinity
    networks:
      - node-network

  # nginx_prod:
  #   image: nitinsaa1999/testproject-backend_nginx_prod
  #   container_name: nitin_nginx_prod
  #   build:
  #     context: D:\Test Project\proxyServer
  #     dockerfile: DockerfileProd
  #   ports:
  #     - "10002:80"
  #   volumes:
  #     - D:\Test Project\proxyServer\nginx.prod.conf:/etc/nginx/nginx.conf:ro 
  #   depends_on:
  #     - backend_node_prod
  #   networks:
  #     - node-network
networks: 
  node-network:
    driver: bridge